AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/**/*
    - test/**/*

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'